apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-of-apps
  namespace: openshift-gitops
spec:
  destination:
    server: 'https://kubernetes.default.svc'
  project: default
  sources:
  - helm:
      valueFiles:
      - values-all.yaml
      - values-{{ .Values.cluster_name }}.yaml
    path: cluster-argocd/app-of-apps/
    repoURL: https://github.com/sector2000/test-argo.git
    targetRevision: HEAD
