{{- if has "cluster-version" .Values.enabled_apps }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-version
  namespace: openshift-gitops
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
  source:
    targetRevision: HEAD
    repoURL: https://github.com/sector2000/test-argo.git
    path: cluster-argocd/cluster-version
    helm:
      valueFiles:
        - values.yaml
      values: |
        {{- toYaml .Values | nindent 8 }}
{{- end }}
