apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-version
  namespace: openshift-gitops
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
  sources:
  - repoURL: https://github.com/sector2000/test-argo.git
    path: cluster-argocd/cluster-version
    targetRevision: HEAD
    helm:
      valueFiles:
      - $app_of_apps/cluster-argocd/app-of-apps/values-all.yaml
      - $app_of_apps/cluster-argocd/app-of-apps/values-{{ .Values.cluster_name }}.yaml
      - values.yaml
  - ref: app_of_apps
    repoURL: https://github.com/sector2000/test-argo.git
    targetRevision: HEAD
