apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test-app
  namespace: openshift-gitops
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
  source:
    targetRevision: HEAD
    repoURL: https://github.com/sector2000/test-argo.git
    path: cluster-argocd/test-app
    helm:
      valueFiles:
        - values-all.yaml
        - values-{{ .Values.cluster_name }}.yaml
      values: |
        {{- toYaml .Values | nindent 8 }}
