apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test-app
  namespace: openshift-gitops
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
  sources:
  - repoURL: https://github.com/sector2000/test-argo.git
    path: cluster-argocd/test-app
    targetRevision: HEAD
    helm:
      valueFiles:
      - $app_of_apps/values-all.yaml
      - $app_of_apps/values-{{ .Values.cluster_name }}.yaml
      - values-all.yaml
      - values-{{ .Values.cluster_name }}.yaml
  - ref: app_of_apps
    repoURL: https://github.com/sector2000/test-argo.git
    path: cluster-argocd/app-of-apps
    targetRevision: HEAD
