apiVersion: v1
kind: ConfigMap
metadata:
  name: release-image-{{ .Values.openshift_version }}
  namespace: openshift-config-managed
  labels:
    release.openshift.io/verification-signatures: ""
binaryData:
  {{ .Values.digest_algorithm }}-{{ .Values.digest_encoded }}: {{ .Values.signature_base64 }}
